#Configuration for Temperature alert system by sms
#Below data is not shared due to privacy issues
SID = 'You can find SID in your Twilio Dashboard' 
AUTH_TOKEN = 'You can find  on your Twilio Dashboard' 
FROM_NUMBER = 'This is the no. generated by Twilio.'
TO_NUMBER = 'This is receiver(your) number.'
API_KEY = 'This is your Cloud accout API key'
DEVICE_ID = 'This is the ID of your IOT device' 